alias ls='lsd --color=always --group-directories-first'
alias ll='lsd -lah --color=always --group-directories-first'
alias cat='bat -A --color always'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias xu='sudo xbps-install -Suv'
alias xin='sudo xbps-install'
alias xr='sudo xbps-remove -Rcon'
alias xl='xbps-query -l'
alias xf='xl | grep'
alias xs='xbps-query -Rs'
alias xd='xbps-query -x'
#alias clrk='sudo vkpurge rm all && sudo rm -rf /var/cache/xbps/*'
alias cleankernel='sudo vkpurge rm $(vkpurge list|sort -r|tail -n +2)'
#alias pong='ping -c 3 1.1.1.1' 
alias ping='ping -c 3 ' 
alias halt='sudo halt'
alias poweroff='sudo poweroff'
alias reboot='sudo reboot'
alias shutdown='sudo shutdown'

#alias lf=lfrun

alias git-bare=' git --git-dir=$HOME/dot2git --work-tree=$HOME'
