# https://alacritty.org/config-alacritty.html
import = [
# uncomment the flavour you want below:
# "~/.config/alacritty/tokyo-night.toml"
# "~/.config/alacritty/tokyo-night-storm.toml"
"~/.config/alacritty/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "None"
opacity = 0.9

[window.padding]
x = 10
y = 10

[font]
size = 14

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[cursor.style]
shape = "Beam"
blinking = "Always"

[keyboard]
bindings = [{key = "Q", mods = "Control", action = "Quit"},]
